"use client"
import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Layout from "./components/layout/Layout";
import Header from "./components/header/Header";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

// export const metadata: Metadata = {
//   title: "Timmy Tech Store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Layout>
            {/* <ToastContainer /> */}
            <Header />
            {children}
          </Layout>
        </Provider>
      </body>
    </html>
  );
}
